extends: eslint-config-sinon

globals:
  ArrayBuffer: false
  Uint8Array: false

env:
  mocha: true

plugins:
  - mocha

rules:
  mocha/no-exclusive-tests: error
  mocha/no-identical-title: error
  mocha/no-nested-tests: error
  mocha/no-sibling-hooks: error
  mocha/no-top-level-hooks: error
  max-nested-callbacks: off
