language: node_js

sudo: false

node_js:
  # https://github.com/nodejs/LTS
  - "6" # ends April 2019
  - "8" # ends December 2019
  - "10"
  - "12"

script:
  - "npm run lint"
  - "npm test"
  - if [ "x$TRAVIS_NODE_VERSION" = "x8" ]; then npm run-script test:headless -- --allow-chrome-as-root; fi